name: myfirstworkflow

on: push

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v2

      - name: Great & count the files
        env:
          STUDENT_NAME: ${{ vars.STUDENT_NAME }}
        run: |
          COUNT=$(find . -type f -not -path './.git/*' | wc -l)
          echo "Hello, $STUDENT_NAME, There are $COUNT files in your repository."