name: myfirstworkflow

on: push

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v2

      - name: Great & count the files
        env:
         STUDENT_NAME: ${{ vars.STUDENT_NAME }}
        run: echo "Hello, ${{ vars.STUDENT_NAME }}!"